# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XmsL19ZtPXtYxoMPPpvP9hHjEyBRjSq2
"""

import numpy as np
import matplotlib.pyplot as plt
import math

